apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dashboard
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-dashboard
  template:
    metadata:
      labels:
        app: redis-dashboard
    spec:
      containers:
        - name: redis-dashboard
          image: redis:7.2

          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-dashboard
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
